- README.md
- docker/data-source-services/network-creation.sh
While setting up a new project, I ran into
```
➜  docker git:(master) ✗ docker network create xxxx-internal
Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```
Apparently from https://stackoverflow.com/a/53838883/455008, this is because Docker caps out at 30 networks. After that and it refuses to work. I thought about deleting old/legacy projects, but that doesn't help things like Jenkins and onboarding.
I think making an internal network at the dev-ops level and just using that network to pivot between php/nginx could work fine. I don't see any immediate concerns for this plan, so pending merge I can cut another release/tag.
So new projects (instead of making their own network) can just define this …
> Support for generic network

- README.md
- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
* We can now support multiple hosts via one management system.
* Start deprecation of specific service networks for one
> Optional PHPMyAdmin + Start deprecation of specific service networks

- examples/laravel/Dockerfile
> fix: correct 7.4 docker to respect new requirements

- CHANGELOG.md
* Removed mysql56
* Deprecated networks that aren't "st-internal"
* Added MariaDB10.3
* Added MariaDB10.4
* Added optional phpMyAdmin
> [Release] v1.2.0

- README.md
* The old network names aren't used (unless your project uses them) and if so, you know that since your scripts/ci do it.
* New toads should not have these networks filling up the 30 limit if they are unused.
* Added missing 10.4 note in readme
> docs: retire old network names + add missing 10.4 note

- README.md
- scripts/db_migrate.sh
```
➜  DevopsToolKit git:(db-migrate) ✗ ./scripts/db_migrate.sh
Welcome to the SDIT DB Migrator (mysql/postgres) 
Select (mysql|postgres):mysql
Enter (FROM) port number:33101
Enter (FROM) database name: redacted
Enter (TO) port number:33103
Enter (TO) database name: redacted
Copying...! 
Copied...! 
➜  DevopsToolKit git:(db-migrate) ✗ 
```
* TLDR - We are upgrading database versions for projects more often and its becoming quite a pain to restore a local db by exporting/importing etc.
> DB Migrator

- CHANGELOG.md
* Retire non `st-internal` network names (not yet removed).
* Remove outdated python and upsource documentation.
* Move yii2-shell docs into /docs
* Add `./scripts/db_migrate` for moving databases between versions of database.
* Update docker templates for latest php74 packages/versions.
> [Release] v1.3.0

- docker/data-source-services/docker-compose.yml
- docs/phpstorm-docker/README.md
This resolves a series of errors that happen when `docker-compose up` is executed.
Example:
```
--- docker/data-source-services ‹master› » docker-compose up --build -d
ERROR: Network nginx-proxy declared as external, but could not be found. Please create the network manually using `docker network create nginx-proxy` and try again.
```
> Remove references to removed networks

- docker/data-source-services/docker-compose.yml
I get a warning on new versions of Docker about `network.external.name` being deprecated in favor of `network.name`.
> fix: Change network name for deprecated yml configuration

- examples/laravel/Dockerfile
Figured this would be good to put into our templates. Since the `latest` tag from docker is bugged in so many ways.
https://vsupalov.com/docker-latest-tag/
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
https://blog.container-solutions.com/docker-latest-confusion
> JEST-226 build: lock docker to composer2

- CHANGELOG.md
In favor for more automation for our open source offerings with less burden of making releases or keeping track of them with a manually generated changelog file.
If anything, we will start an `UPGRADE.md` used for breaking changes.
Context - https://github.com/sourcetoad/DevopsToolKit/pull/33
> docs: deprecate changelog

- README.md
- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
Going forward we are going to only track LTS versions for Maria. So that means 10.4/10.5 are deprecated and the remaining few projects on it will be migrated to 10.6/10.11.
> feat: add maria 10.11, drop 10.3

- docker/data-source-services/docker-compose.yml
- docker/data-source-services/network-creation.sh
- docker/data-source-tools/docker-compose.yml
Version `2` does not properly handle external/name networks. So our line was misleading in referring to an external network. 
There is an active, unclosed bug in docker https://github.com/docker/compose/issues/10797 which in the latest update (4.21.1 (114176)) has caused our containers to fail booting.
```
network st-internal was found but has incorrect label com.docker.compose.network set to ""
```
I'm guessing we'll get a hotfix since it seems unlikely that we have to track or workaround this. So if your project fails you might have to remake our network via:
```
stop docker
docker network rm -f st-internal
docker network create st-internal --label "com.docker.compose.network=default
```
Bring projects up again. If they fail with:
```
Error response from daemon: network …
```
> build: support external networks and labeled external network

- README.md
- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
As we've learned with newer projects and requirements. A few projects have inlined their DB requirements due to "reasons".
So we've found over time - more and more databases leave this project. Its true main purpose has been just reversing HTTP ports so projects don't collide.
So we retire the non-lts MariaDB versions here. The LTS will be the only ones that remain or are tracked.
> Remove MariaDB 10.4 & 10.5

- bin/hop
- Supports running commands like `hop up -d --remove-orphans`
- @iBotPeaches let us know if this is potentially problematic in your eyes and we can consider something like a `hop dss` or `hop rebuild` command instead.
- Adds a `hop go` utility that runs `hop up -d` and `hop yarn dev` or `hop npm run dev` as one command for easy boot up of a project.
- Can also run `hop go *` to run `hop yarn *` or `hop npm run *`. Mostly applicable for the `hop go build` scenario where you want a production build of your project.
> Hop improvements

- .github/workflows/linter.yml
Updating the github actions to use newer node version by default to get rid of warnings of older Node versions being used.
- actions/checkout: v2 -> v4
- github/super-linter/slim: v4 -> v5
> JEST-1246 Fix lint warnings on DevopsToolKit

- docker/data-source-tools/docker-compose.yml
This will make 10.11 the default, with a click to move to 10.6. That seems preferred. We default to the newest.
> build: move order of db from newest to oldest

- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
With `docker-compose` gone now - nothing reads `version` anymore. Thus we get warnings.
```
WARN[0000] DevopsToolKit/docker/data-source-services/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
I'm sure if someone hasn't taken the upgrade that removes `docker-compose` for `docker compose` - they will soon.
> build: remove 'version' property

- bin/hop
Currently if a hop command fails, it will exit with success rather than the original error code. This isn't an issue in most cases since we don't use it in scripts or CI, but it's still helpful to pass any error codes up so multiple commands run with `&&` don't continue down the chain.
> Make hop pass through error

- README.md
- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
* With most, if not all, projects on 10.11. We can start the deprecation/closure of 10.6 and start an upgrade of projects to 11.4
* https://endoflife.date/mariadb
Timelines
* 10.6 - 06 Jul 2026
* 10.11 -16 Feb 2028
* 11.4 - 29 May 2029
A later PR will actually remove 10.6 once confirmation that no more active projects are still on 10.6.
> MariaDB 11.4 - LTS

- README.md
- docker/data-source-services/docker-compose.yml
- docker/data-source-tools/docker-compose.yml
* We no longer have any active projects on MariaDB 10.6.
* New projects are 11.4 - existing projects are on upgrade paths to 11.4.
* 10.11 is now deprecated - new projects will prefer 11.4.
> Remove MariaDB 10.6
